asana:
  workspace: 5669522480945
  picturesId: 29414423499815
  graphicsId: 28686036279645
  baseUrl: https://app.asana.com/api/1.0
spring:
  profiles:
    active: production
logging:
  level:
    com.ft: DEBUG

