asana:
  workspace: 36628479813449
  picturesId: 36788370362617
  graphicsId: 36788370362615
---
logging:
    level:
      com.ft: DEBUG
      org.springframework.security: INFO
      com.netflix.discovery: 'OFF'
---
report:
  hostDomain: ft.com
  desks:
    Companies:
      projectId: 37532256694653
      projectName: Companies Topics
      groupTags: true
      premiumTags:
        - Finserv
        - Comment
    World:
      projectId: 42589704501506
      projectName: World Topics
      groupTags: true
      premiumTags: []
    UK:
      projectId: 37532256694667
      projectName: UK Topics
      groupTags: true
      premiumTags: []
    Markets:
      projectId: 39486514321993
      projectName: Markets Topics
      groupTags: true
      premiumTags: []
    Lex:
      projectId: 40652275263716
      projectName: Lex Topics
      groupTags: true
      premiumTags: []
---
backup:
  google:
    rootFolder: asana_staging_backup
    sharedWith:
      users:
        - lucas.gluchowski@ft.com
        - stuart.turner@ft.com
        - claire.powell@ft.com
        - yolande.leung@ft.com
        - mo.shawwa@ft.com
