asana:
  workspace: 36628479813449
  picturesId: 36788370362617
  graphicsId: 36788370362615
---
logging:
    level:
      com.ft: DEBUG
      org.springframework.security: INFO
      com.netflix.discovery: 'OFF'
---
report:
  hostDomain: ft.com
  desks:
    Companies:
      projects:
        -
          id: 37532256694653
          name: Companies Topics
      groupTags: true
      premiumTags:
        - Finserv
        - TMT
        - Industry
        - Energy
        - Consumer
        - Comment
    World:
      projects:
        -
          id: 42589704501506
          name: World Topics
      groupTags: true
      premiumTags: []
    UK:
      projects:
        -
          id: 37532256694667
          name: UK Topics
      groupTags: false
      premiumTags: []
    Markets:
      projects:
        -
          id: 39486514321993
          name: Markets Topics
      groupTags: false
      premiumTags: []
    Lex:
      projects:
        -
          id: 40652275263716
          name: Lex Topics
      projectId: 40652275263716
      projectName: Lex Topics
      groupTags: false
      premiumTags: []
    FT Money:
      projects:
        -
          id: 42553710401200
          name: FT Money Topics
      groupTags: false
      premiumTags: []
    FTfm:
      projects:
        -
          id: 50849038952169
          name: FTfm Topics
      groupTags: false
      premiumTags: []
    Comment and Leaders:
      projects:
        -
          id: 55126358623999
          name: Comment and Leaders Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Business Life:
      projects:
        -
          id: 52535481220644
          name: Business Life Daily
          primary: false
        -
          id: 55126358624001
          name: Business Life Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Big Read:
      projects:
        -
          id: 52535481220647
          name: Big Read Daily
          primary: false
        -
          id: 55126358623997
          name: Big Read Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Features Production:
      projects:
        -
          id: 52535481220650
          name: Features Production Daily Plan
          primary: false
        -
          id: 55126358624003
          name: Features Production Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
---
backup:
  google:
    rootFolder: asana_staging_backup
    sharedWith:
      users:
        - lucas.gluchowski@ft.com
        - stuart.turner@ft.com
        - claire.powell@ft.com
        - yolande.leung@ft.com
        - mo.shawwa@ft.com
