asana:
  workspace: 5669522480945
  picturesId: 29414423499815
  graphicsId: 28686036279645
  baseUrl: https://app.asana.com/api/1.0
  authorizedTeams:
    - Companies
    - World
    - UK
---
server:
  port: 8080
---
security:
  basic:
    enabled: false
  ignored: /,/health,/favicon.ico,/index.html,/js/**,/css/**
  sessions: ALWAYS
---
logging:
    level:
      com.ft: DEBUG
      org.springframework.security: INFO
      com.netflix.discovery: 'OFF'
---
spring:
  oauth2:
    sso:
      loginPath: /login
      logoutPath: /logout
    client:
      clientId: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth?hd=ft.com
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me/openIdConnect
      preferTokenInfo: false
  thymeleaf.cache: false

---
report:
  hostDomain: ft.com
  desks:
    Companies:
      projectId: 5669522480945
      premiumTags:
        - Finserv
        - TMT
        - Industry
        - Energy
        - Consumer
        - Comment
    World:
      projectId: 28687437659749
      premiumTags: []
    UK:
      projectId: 33167799661044
      premiumTags:
        - Parly
        - Business
        - Economy
        - Public Policy
        - Legal & Regulation
        - Scotland
        - UK Regions
        - Arts & Culture
        - Sport
        - London
---
management:
  security:
    enabled: false
  health:
    diskspace:
      enabled: false
---
endpoints:
  enabled: false
  health:
    enabled: true
