asana:
  workspace: 324300775153
  picturesId: 29414423499815
  graphicsId: 25587620489018
  baseUrl: https://app.asana.com/api/1.0
spring:
  profiles:
    active: production
logging:
  level:
    com.ft: DEBUG

