asana:
  workspace: 36628479813449
  picturesId: 36788370362617
  graphicsId: 36788370362615
  authorizedTeams:
    - Companies
    - Desk Name
    - UK
---
logging:
    level:
      com.ft: DEBUG
      org.springframework.security: INFO
      com.netflix.discovery: 'OFF'
---
report:
  hostDomain: ft.com
  desks:
    Companies:
      projectId: 37532256694653
    Desk Name:
      projectId: 36788370362611
    UK:
      projectId: 37532256694667
    Markets:
      projectId: 39486514321993
---
backup:
  google:
    shareWithUsers:
      - lucas.gluchowski@ft.com
      - stuart.turner@ft.com
      - claire.powell@ft.com