asana:
  workspace: 36628479813449
  bots:
    -
      projectId: 112192541246514
      name: scheduled
      apiKey: ${ASANA_SCHEDULED_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 138637266190858
      name: overnight
      apiKey: ${ASANA_OVERNIGHT_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 90407076979571
      name: design
      apiKey: ${ASANA_DESIGN_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 36788370362617
      name: picture
      apiKey: ${ASANA_PICTURES_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 36788370362615
      name: graphicsEmail
      apiKey: ${ASANA_GRAPHICS_DUE_DATE_BOT_KEY}
      runnerBean: taskDueDateTaskRunner
      runInterval: 20_000
    -
      projectId: 36788370362615
      name: graphics
      apiKey: ${ASANA_GRAPHICS_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 43400279162108
      name: social
      apiKey: ${ASANA_SOCIAL_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 144923892603882
      name: front UK
      apiKey: ${ASANA_FRONT_UK_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 144923892603883
      name: front US
      apiKey: ${ASANA_FRONT_US_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      name: backup
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: backupTaskRunner
      runInterval: 3_600_000 # one hour in milliseconds
    -
      name: check for changes
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: checkForChangesTaskRunner
      runInterval: 300_000 # five minutes in milliseconds
    -
      name: Remove old backup files
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: removeOldBackupFilesTaskRunner
      runInterval: 3_600_000 # one hour in milliseconds
---
logging:
    level:
      com.ft: DEBUG
      org.springframework.security: INFO
      com.netflix.discovery: 'OFF'
---
report:
  hostDomain: ft.com
  desks:
    Companies:
      projects:
        -
          id: 37532256694653
          name: Companies Topics
      groupTags: true
      showProjects: false
      premiumTags:
        - Finserv
        - TMT
        - Industry
        - Energy
        - Consumer
        - Comment
    World:
      projects:
        -
          id: 42589704501506
          name: World Topics
      groupTags: true
      premiumTags: []
      showProjects: false
    UK:
      projects:
        -
          id: 37532256694667
          name: UK Topics
      groupTags: false
      premiumTags: []
      showProjects: false
    Markets:
      projects:
        -
          id: 39486514321993
          name: Markets Topics
      groupTags: false
      premiumTags: []
      showProjects: false
    Lex:
      projects:
        -
          id: 40652275263716
          name: Lex Topics
      projectId: 40652275263716
      projectName: Lex Topics
      groupTags: false
      premiumTags: []
      showProjects: false
    FT Money:
      projects:
        -
          id: 42553710401200
          name: FT Money Topics
      groupTags: false
      premiumTags: []
      showProjects: true
    FTfm:
      projects:
        -
          id: 50849038952169
          name: FTfm Topics
      groupTags: false
      premiumTags: []
      showProjects: false
    Comment and Leaders:
      projects:
        -
          id: 55126358623999
          name: Comment and Leaders Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
      showProjects: false
    Business Life:
      projects:
        -
          id: 52535481220644
          name: Business Life Daily
          primary: false
        -
          id: 55126358624001
          name: Business Life Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
      showProjects: true
    Big Read:
      projects:
        -
          id: 52535481220647
          name: Big Read Daily
          primary: false
        -
          id: 55126358623997
          name: Big Read Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
      showProjects: true
    Features Production:
      projects:
        -
          id: 52535481220650
          name: Features Production Daily Plan
          primary: false
        -
          id: 55126358624003
          name: Features Production Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
      showProjects: true
    Video:
      projects:
        -
          id: 59466798455336
          name: Videos in production
      groupTags: false
      premiumTags: []
    Weekend:
      projects:
        -
          id: 68145410531982
          name: Arts
        -
          id: 81987306808740
          name: Style
        -
          id: 81987306808741
          name: Books
        -
          id: 81987306808739
          name: Travel
        -
          id: 81987306808742
          name: Food & Drink
        -
          id: 81987306808743
          name: Property
        -
          id: 81987306808744
          name: Columnists
        -
          id: 81987306808745
          name: Lunch with the FT
        -
          id: 81987306808746
          name: Life
      groupTags: true
      premiumTags: []
      showProjects: false
      reportCategory: WEEKEND
---
backup:
  google:
    rootFolder: asana_staging_backup
    sharedWith:
      users:
        - lucas.gluchowski@ft.com
        - stuart.turner@ft.com
        - claire.powell@ft.com
        - ola.okejimi@ft.com
        - mo.shawwa@ft.com
