asana:
  bots:
    -
      projectId: 108406100432614
      name: scheduled
      apiKey: ${ASANA_SCHEDULED_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 138637266190867
      name: Homepage UK
      apiKey: ${ASANA_OVERNIGHT_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 164832224821432
      name: homepage international
      apiKey: ${ASANA_HOMEPAGE_INTL_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 102068710859175
      name: design
      apiKey: ${ASANA_DESIGN_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 29414423499815
      name: picture
      apiKey: ${ASANA_PICTURES_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 28686036279645
      name: graphics
      apiKey: ${ASANA_GRAPHICS_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 28686036279645
      name: graphicsEmail
      apiKey: ${ASANA_GRAPHICS_DUE_DATE_BOT_KEY}
      runnerBean: taskDueDateTaskRunner
      runInterval: 20_000
    -
      projectId: 37074265374689
      name: social
      apiKey: ${ASANA_SOCIAL_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 144945446998057
      name: front UK
      apiKey: ${ASANA_FRONT_UK_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 144945446998056
      name: front US
      apiKey: ${ASANA_FRONT_US_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 181309235948088
      name: sunday plan
      apiKey: ${ASANA_SUNDAY_PLAN_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      name: backup
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: backupTaskRunner
      runInterval: 3_600_000 # one hour in milliseconds
    -
      name: check for changes
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: checkForChangesTaskRunner
      runInterval: 300_000 # five minutes in milliseconds
    -
      name: Remove old backup files
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: removeOldBackupFilesTaskRunner
      runInterval: 3_600_000 # one hour in milliseconds
backup:
  google:
    rootFolder: asana_backup
    sharedWith:
      users: []
      groups:
        - asana.backup@ft.com
        - digitalnewsroomprogramme@ft.com

management:
  add-application-context-header: false
spring:
  thymeleaf.cache: true
report:
  hostDomain: ft.com
  desks:
    Companies:
      projects:
        -
          id: 32896507461944
          name: Companies Topics
      groupTags: true
      premiumTags:
        - Finserv
        - TMT
        - Industry
        - Energy
        - Consumer
        - Comment
    World:
      projects:
        -
          id: 28687437659749
          name: World Topics
      groupTags: true
      premiumTags: []
    UK:
      projects:
        -
          id: 33167799661044
          name: UK Topics
      groupTags: false
      premiumTags: []
    Markets:
      projects:
        -
          id: 32052433501773
          name: Markets Topics
      groupTags: false
      premiumTags: []
    Lex:
      projects:
        -
          id: 38342535680181
          name: Lex Topics
      groupTags: false
      premiumTags: []
    FT Money:
      projects:
        -
          id: 42850013094580
          name: FT Money Topics
      groupTags: false
      premiumTags: []
    FTfm:
      projects:
        -
          id: 48184142077370
          name: FTfm Topics
      groupTags: false
      premiumTags: []
    Comment and Leaders:
      projects:
        -
          id: 48119832269549
          name: Comment and Leaders Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Work & Careers:
      projects:
        -
          id: 50514423082937
          name: Work & Careers Daily
          primary: false
        -
          id: 50514423082939
          name: Business Life Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Big Read:
      projects:
        -
          id: 50514423082943
          name: Big Read Topics
          primary: false
        -
          id: 50514423082945
          name: Big Read Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Features Production:
      projects:
        -
          id: 50514423082949
          name: Features Production Daily Plan
          primary: false
        -
          id: 50514423082952
          name: Features Production Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Video:
      projects:
        -
          id: 56381527297830
          name: Videos in production
      groupTags: false
      premiumTags: []
    Weekend:
      projects:
        -
          id: 172199181928664
          name: Arts
        -
          id: 172199181928674
          name: House & Home
        -
          id: 172199181928665
          name: Style
        -
          id: 172199181928666
          name: Books
        -
          id: 172199181928667
          name: Travel
        -
          id: 172199181928673
          name: Food & Drink
        -
          id: 172199181928670
          name: Life & Arts
        -
          id: 172199181928675
          name: Magazine
      groupTags: true
      premiumTags: []
      showProjects: false
      reportCategory: WEEKEND
