asana:
  workspace: 5669522480945
  bots: []
  baseUrl: https://app.asana.com/api/1.0
  authorizedTeams:
    - Companies
    - World
    - UK
    - Markets
    - Lex
    - FT Money
    - FTfm
    - Comment and Leaders
    - Business Life
    - Big Read
    - Features Production
    - Video
    - Weekend
  emailTeams:
    -
      name: Video
      email: ${VIDEO_PLANNER_EMAIL}
    -
      name: Weekend
      email: ${WEEKEND_PROJECT_EMAIL}
  tags:
    Companies: COS
    World: WN
    UK: UKN
    Pictures: PIC
---
server:
  port: 8080
---
security:
  basic:
    enabled: false
  ignored: /health,/logout,/logout/**,/favicon.ico,/js/**,/css/**,/changes/projects
  sessions: ALWAYS
---
logging:
    level:
      com.ft: DEBUG
      org.springframework.security: INFO
      com.netflix.discovery: 'OFF'
---
security:
  oauth2:
    sso:
      loginPath: /login
    client:
      clientId: ${OAUTH_CLIENT_ID}
      clientSecret: ${OAUTH_CLIENT_SECRET}
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth?hd=ft.com
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
    resource:
      userInfoUri: https://www.googleapis.com/plus/v1/people/me/openIdConnect
      preferTokenInfo: false
spring:
  thymeleaf.cache: false
  mail:
      host: smtp.svc.ft.com
      port: 25
---
report:
  hostDomain: ft.com
  desks: []
---
management:
  security:
    enabled: false
  health:
    diskspace:
      enabled: false
---
endpoints:
  enabled: false
  health:
    enabled: true
---
backup:
  google:
    privateKey: ${GOOGLE_API_PRIVATE_KEY}
    privateKeyId: ${GOOGLE_API_PRIVATE_KEY_ID}
    clientEmail: ${GOOGLE_API_CLIENT_EMAIL}
    clientId: ${GOOGLE_API_CLIENT_ID}
    type: service_account
    rootFolder: asana_backup
    sharedWith:
      users: []
      groups: []
---
notify:
  slackWebHookUrl: ${SLACK_WEBHOOK}
---
sendgrid:
  apikey: ${SENDGRID_APIKEY}
