backup:
  google:
    rootFolder: asana_backup
    sharedWith:
      users: []
      groups:
        - prod@ft.com
        - digitalnewsroomprogramme@ft.com

management:
  add-application-context-header: false

report:
  hostDomain: ft.com
  desks:
    Companies:
      projectId: 32896507461944
      projectName: Companies Topics
      groupTags: true
      premiumTags:
        - Finserv
        - TMT
        - Industry
        - Energy
        - Consumer
        - Comment
    World:
      projectId: 28687437659749
      projectName: World Topics
      groupTags: true
      premiumTags: []
    UK:
      projectId: 33167799661044
      projectName: UK Topics
      groupTags: false
      premiumTags: []
    Markets:
      projectId: 32052433501773
      projectName: Markets Topics
      groupTags: false
      premiumTags: []
    Lex:
      projectId: 38342535680181
      projectName: Lex Topics
      groupTags: false
      premiumTags: []
    FT Money:
      projectId: 42850013094580
      projectName: FT Money Topics
      groupTags: false
      premiumTags: []
    FTfm:
      projectId: 48184142077370
      projectName: FTfm Topics
      groupTags: false
      premiumTags: []
    Comment and Leaders:
      projects:
        -
          id: 48131968026045
          name: Comment and Leaders Daily
          primary: false
        -
          id: 48119832269549
          name: Comment and Leaders Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Business Life:
      projects:
        -
          id: 50514423082937
          name: Business Life Daily
          primary: false
        -
          id: 50514423082939
          name: Business Life Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Big Read:
      projects:
        -
          id: 50514423082943
          name: Big Read Daily
          primary: false
        -
          id: 50514423082945
          name: Big Read Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
    Features Production:
      projects:
        -
          id: 50514423082949
          name: Features Production Daily Plan
          primary: false
        -
          id: 50514423082952
          name: Features Production Forward Plan
          primary: true
      groupTags: false
      premiumTags: []