asana:
  workspace: 36628479813449
  bots:
    -
      projectId: 112192541246514
      name: scheduled
      apiKey: ${ASANA_SCHEDULED_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 138637266190858
      name: Homepage UK
      apiKey: ${ASANA_OVERNIGHT_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 164969270401862
      name: homepage international
      apiKey: ${ASANA_HOMEPAGE_INTL_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 90407076979571
      name: design
      apiKey: ${ASANA_DESIGN_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 36788370362617
      name: picture
      apiKey: ${ASANA_PICTURES_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 36788370362615
      name: graphicsEmail
      apiKey: ${ASANA_GRAPHICS_DUE_DATE_BOT_KEY}
      runnerBean: taskDueDateTaskRunner
      runInterval: 20_000
    -
      projectId: 37532256694653
      name: companiesEmail
      apiKey: ${ASANA_COMPANIES_DUE_DATE_BOT_KEY}
      runnerBean: taskDueDateTaskRunner
      runInterval: 20_000
    -
      projectId: 36788370362615
      name: graphics
      apiKey: ${ASANA_GRAPHICS_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 43400279162108
      name: social
      apiKey: ${ASANA_SOCIAL_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 144923892603882
      name: 2ndfrontsbot
      apiKey: ${ASANA_FRONT_UK_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 144923892603883
      name: Frontsbot
      apiKey: ${ASANA_FRONT_US_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      projectId: 180515453379296
      name: sunday plan
      apiKey: ${ASANA_SUNDAY_PLAN_KEY}
      runnerBean: taskOnProjectTaskRunner
      runInterval: 20_000
    -
      name: backup
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: backupTaskRunner
      runInterval: 3_600_000 # one hour in milliseconds
    -
      name: check for changes
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: checkForChangesTaskRunner
      runInterval: 3_600_000 # one hour in milliseconds
    -
      name: Remove old backup files
      apiKey: ${ASANA_REPORT_PERSONAL_KEY} # name will be aligned with standard once reportAsanaClient is removed
      runnerBean: removeOldBackupFilesTaskRunner
      runInterval: 3_600_000 # one hour in milliseconds
---
logging:
    level:
      com.ft: DEBUG
      org.springframework.security: INFO
      com.netflix.discovery: 'OFF'
---
report:
  hostDomain: ft.com
  desks:
    Companies:
      projects:
        -
          id: 37532256694653
          name: Companies Topics
      groupTags: true
      showProjects: false
      premiumTags:
        - Finserv
        - TMT
        - Industry
        - Energy
        - Consumer
        - Comment
    World:
      projects:
        -
          id: 42589704501506
          name: World Topics
      groupTags: true
      premiumTags: []
      showProjects: false
    UK:
      projects:
        -
          id: 37532256694667
          name: UK Topics
      groupTags: false
      premiumTags: []
      showProjects: false
    Markets:
      projects:
        -
          id: 39486514321993
          name: Markets Topics
      groupTags: false
      premiumTags: []
      showProjects: false
    Lex:
      projects:
        -
          id: 40652275263716
          name: Lex Topics
      projectId: 40652275263716
      projectName: Lex Topics
      groupTags: false
      premiumTags: []
      showProjects: false
    FTfm:
      projects:
        -
          id: 50849038952169
          name: FTfm Topics
      groupTags: false
      premiumTags: []
      showProjects: false
    Comment and Leaders:
      projects:
        -
          id: 55126358623999
          name: Comment and Leaders Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
      showProjects: false
    Work & Careers:
      projects:
        -
          id: 52535481220644
          name: Work & Careers Daily
          primary: false
        -
          id: 55126358624001
          name: Business Life Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
      showProjects: true
    Big Read:
      projects:
        -
          id: 52535481220647
          name: Big Read Daily
          primary: false
        -
          id: 55126358623997
          name: Big Read Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
      showProjects: true
    Features Production:
      projects:
        -
          id: 52535481220650
          name: Features Production Daily Plan
          primary: false
        -
          id: 55126358624003
          name: Features Production Forward Plan
          primary: true
      groupTags: false
      premiumTags: []
      showProjects: true
    Video:
      projects:
        -
          id: 59466798455336
          name: Videos in production
      groupTags: false
      premiumTags: []
    Weekend:
      projects:
        -
          id: "81987306808740,81987306808741,81987306808739,68145410531982,81987306808746"
          name: "Style,Books,Travel,Arts,Life & Art"
        -
          id: "81987306808742,94237279249298"
          name: "Food & Drink, Magazine"
        -
          id: 81987306808743
          name: House & Home
        -
          id: "192226175037125,192226175037126"
          name: "FT Money Ideas,FT Money Topics"
      groupTags: true
      premiumTags: []
      showProjects: true
      reportCategory: WEEKEND
  displayTitles:
    81987306808740: Style
    81987306808741: Books
    81987306808739: Travel
    68145410531982: Arts
    81987306808746: Life & Art
    81987306808742: Food & Drink
    94237279249298: Magazine
    192226175037125: FT Money Ideas
    192226175037126: FT Money Topics
---
backup:
  google:
    rootFolder: asana_staging_backup
    sharedWith:
      users:
        - lucas.gluchowski@ft.com
        - stuart.turner@ft.com
        - claire.powell@ft.com
        - ola.okejimi@ft.com
        - mo.shawwa@ft.com
