asana:
  workspace: 36628479813449
  picturesId: 36788370362617
  graphicsId: 36788370362615
  socialId: 43400279162108
  interactivesId: 43400279162111
  videoId: 43400279162114
---
logging:
    level:
      com.ft: DEBUG
      org.springframework.security: INFO
      com.netflix.discovery: 'OFF'
---
report:
  hostDomain: ft.com
  desks:
    Companies:
      projectId: 37532256694653
    World:
      projectId: 38323966333074
    UK:
      projectId: 37532256694667
    Markets:
      projectId: 39486514321993
    Lex:
      projectId: 40652275263716
---
backup:
  google:
    rootFolder: asana_staging_backup
    sharedWith:
      users:
        - lucas.gluchowski@ft.com
        - stuart.turner@ft.com
        - claire.powell@ft.com