backup:
  google:
    rootFolder: asana_backup
    sharedWith:
      users: []
      groups:
        - prod@ft.com
        - digitalnewsroomprogramme@ft.com

management:
  add-application-context-header: false

report:
  hostDomain: ft.com
  desks:
    Companies:
      projectId: 32896507461944
      projectName: Companies Topics
      groupTags: true
      premiumTags:
        - Finserv
        - TMT
        - Industry
        - Energy
        - Consumer
        - Comment
    World:
      projectId: 28687437659749
      projectName: World Topics
      groupTags: true
      premiumTags: []
    UK:
      projectId: 33167799661044
      projectName: UK Topics
      groupTags: false
      premiumTags: []
    Markets:
      projectId: 32052433501773
      projectName: Markets Topics
      groupTags: false
      premiumTags: []
    Lex:
      projectId: 38342535680181
      projectName: Lex Topics
      groupTags: false
      premiumTags: []
    FT Money:
      projectId: 42850013094580
      projectName: FT Money Topics
      groupTags: false
      premiumTags: []
    FTfm:
      projectId: 48184142077370
      projectName: FTfm Topics
      groupTags: false
      premiumTags: []
    Comment and Leaders:
      projectId: 48131968026045
      projectName: Comment and Leaders Daily
      groupTags: false
      premiumTags: []
    Business Life:
      projectId: 50514423082937
      projectName: Business Life Daily
      groupTags: false
      premiumTags: []
    Big Read:
      projectId: 50514423082943
      projectName: Big Read Daily
      groupTags: false
      premiumTags: []
    Features Production:
      projectId: 50514423082949
      projectName: Features Production Daily Plan
      groupTags: false
      premiumTags: []