backup:
  google:
    rootFolder: asana_backup
    sharedWith:
      users: []
      groups:
        - prod@ft.com
        - digitalnewsroomprogramme@ft.com

management:
  add-application-context-header: false